/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006b5f",
        "on-secondary-fixed": "#00201c",
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "secondary-fixed": "#bbece2",
        "on-primary-container": "#00423b",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#3d6b63",
        "secondary-container": "#b9e9e0",
        "primary-container": "#14b8a6",
        "secondary-fixed-dim": "#a0d0c6",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-primary-fixed-variant": "#005048",
        "on-tertiary-container": "#6c2106",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#bbcac6",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb59e",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbd0",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "primary": "#006b5f",
        "tertiary-container": "#f38764",
        "tertiary": "#9b4426",
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#7c2d11",
        "on-tertiary-fixed": "#3a0b00",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "inverse-primary": "#4fdbc8",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#1f4e47",
        "primary-fixed-dim": "#4fdbc8",
        "outline": "#6c7a77",
        "surface-dim": "#d8dadc",
        "primary-fixed": "#71f8e4",
        "on-primary": "#ffffff",
        "secondary": "#38665f",
        "on-surface-variant": "#3c4947",
        "on-background": "#191c1e"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
